update project config

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,3 +1,8 @@
+# SPDX-FileCopyrightText: © Sebastian Thomschke and contributors.
+# SPDX-FileContributor: Sebastian Thomschke
+# SPDX-License-Identifier: EPL-2.0
+# SPDX-ArtifactOfProjectHomePage: https://github.com/sebthom/extra-syntax-highlighting-eclipse-plugin
+#
 # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
 name: Build
 
@@ -46,11 +51,20 @@ env:
   KEYSTORE_PATH: /tmp/sebthom.github.io.p12
   KEYSTORE_PW: whatever
 
+
 jobs:
 
-  build:
+  ###########################################################
+  maven-build:
+  ###########################################################
     runs-on: ubuntu-latest
-    concurrency: ci-${{ github.ref }}
+
+
+    # https://docs.github.com/en/actions/using-jobs/using-concurrency
+    concurrency:
+      group: ${{ github.workflow }}-${{ github.ref }}
+      cancel-in-progress: false
+
 
     steps:
     - name: Show environment variables
@@ -60,6 +74,7 @@ jobs:
     - name: Git Checkout
       uses: actions/checkout@v4 # https://github.com/actions/checkout
 
+
     - name: Verify Syntax Registration
       run: |
         set -euo pipefail
@@ -67,19 +82,18 @@ jobs:
         pip install ruamel.yaml
         python plugin/verify-syntax-registrations.py
 
-    - name: Configure fast APT repository mirror
-      uses: vegardit/fast-apt-mirror.sh@v1
-
-
-    - name: "Install: xvfb"
-      run: sudo apt-get install -y xvfb
-
 
     - name: "Install: JDK ${{ env.JAVA_VERSION }}"
       uses: actions/setup-java@v4 # https://github.com/actions/setup-java
       with:
         distribution: temurin
         java-version: ${{ env.JAVA_VERSION }}
+
+
+    - name: "Install: Maven"
+      uses: stCarolas/setup-maven@v4.5 # https://github.com/stCarolas/setup-maven
+      with:
+        maven-version: 3.9.6
 
 
     - name: "Cache: Restore"
@@ -92,12 +106,6 @@ jobs:
           !~/.m2/repository/.cache/tycho/https/raw.githubusercontent.com
           !~/.m2/repository/*SNAPSHOT*
         key: ${{ runner.os }}-${{ hashFiles('build.target') }}-${{ hashFiles('**/pom.xml') }}
-
-
-    - name: "Install: Maven"
-      uses: stCarolas/setup-maven@v4.5 # https://github.com/stCarolas/setup-maven
-      with:
-        maven-version: 3.9.5
 
 
     - name: Get Signing Certificate
@@ -117,7 +125,6 @@ jobs:
 
 
     - name: Build with Maven
-      id: maven-build
       env:
         GITHUB_USER: ${{ github.actor }}
         GITHUB_API_KEY: ${{ github.token }}
@@ -136,8 +143,7 @@ jobs:
         echo "  -> MAVEN_OPTS: $MAVEN_OPTS"
         export MAVEN_OPTS
 
-        # prevent "org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]"
-        xvfb-run mvn \
+        mvn \
           --errors \
           --update-snapshots \
           --batch-mode \
@@ -233,6 +239,7 @@ jobs:
         GH_TOKEN: ${{ github.token }}
       run: |
         gh extension install actions/gh-actions-cache
+        # "|| true" is to avoid "Error: Resource not accessible by integration" from failing the job 
         gh actions-cache delete ${{ steps.cache-restore.outputs.cache-primary-key }} --confirm || true
 
     - name: "Cache: Update"
@@ -265,8 +272,48 @@ jobs:
           echo "start_ssh_session=true" | tee -a "$GITHUB_OUTPUT"
         fi
 
+
     - name: "SSH session for debugging: start"
       uses: mxschmitt/action-tmate@v3 # https://github.com/mxschmitt/action-tmate
       if: always() && steps.DEBUG_SSH_SESSSION_CHECK.outputs.start_ssh_session
       with:
         limit-access-to-actor: ${{ inputs.debug-with-ssh-only-for-actor }}
+
+
+  ###########################################################
+  dependabot-pr-auto-merge:
+  ###########################################################
+    needs: maven-build
+    if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
+    runs-on: ubuntu-latest
+
+    concurrency: dependabot-pr-auto-merge
+
+    permissions:
+      contents: write
+      pull-requests: write
+
+    steps:
+    - name: Dependabot metadata
+      id: metadata
+      uses: dependabot/fetch-metadata@v1 # https://github.com/dependabot/fetch-metadata/
+      with:
+        github-token: "${{ secrets.GITHUB_TOKEN }}"
+
+
+    - name: Enable auto-merge for Dependabot PRs
+      if: |
+        ${{
+          (
+            steps.dependabot-metadata.outputs.package-ecosystem == 'github-actions' && 
+            steps.metadata.outputs.update-type == 'version-update:semver-major'
+          ) || (
+            steps.dependabot-metadata.outputs.package-ecosystem == 'maven' && 
+            steps.metadata.outputs.update-type == 'version-update:semver-minor'
+          )
+        }}
+      run: |
+        gh pr merge --auto --rebase "$PR_URL"
+      env:
+        PR_URL: ${{github.event.pull_request.html_url}}
+        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
